
steps:
  - name: node:10.15.1
    entrypoint: /bin/bash
    args: ["build.sh"]
    env:
    - 'API_KEY=$_API_KEY'
    - 'AUTH_DOMAIN=$_AUTH_DOMAIN'
    - 'PROJECT_ID=$PROJECT_ID'
  - name: node:10.15.1
    entrypoint: yarn
    args: ["install"]
  - name: node:10.15.1
    entrypoint: yarn
    args: ["add", "firebase-tools"]
  - name: node:10.15.1
    entrypoint: yarn
    args: ["build"]
  - name: "node:10.15.1"
    entrypoint: "./node_modules/.bin/firebase"
    args: ["deploy", "--project", "$PROJECT_ID", "--token", "$_TOKEN"]

# readmore https://www.crowdform.co.uk/