
steps:
  - name: node:10.15.1
    entrypoint: /bin/bash
    args: ["-c", "echo GATSBY_API_KEY=$_API_KEY >> .env.production", "echo GATSBY_AUTH_DOMAIN=$_AUTH_DOMAIN >> .env.production", "echo GATSBY_PROJECT_ID=$PROJECT_ID >> .env.production", "cat .env.production"]
  - name: node:10.15.1
    entrypoint: yarn
    args: ["install"]
  - name: node:10.15.1
    entrypoint: yarn
    args: ["add", "firebase-tools"]
  - name: node:10.15.1
    entrypoint: yarn
    args: ["build"]
  - name: "node:10.15.1"
    entrypoint: "./node_modules/.bin/firebase"
    args: ["deploy", "--project", "$PROJECT_ID", "--token", "$_TOKEN"]

# readmore https://www.crowdform.co.uk/